/**
 * OLL algs from https://jperm.net/algs/oll. Go check his YouTube channel.
 */
export const OLLS = [
  "R U R' U' R U' R' F' U' F R U R'",
  "F R' F R2 U' R' U' R U R' F2",
  "R U R' U R U2 R' F R U R' U' F'",
  "R' U' R U' R' U2 R F R U R' U' F'",
  "L F' L' U' L U F U' L'",
  "R' F R U R' U' F' U R",
  "R U R2 U' R' F R U R U' F'",
  "R' U' R' F R F' U R",
  "r U R' U' r' R U R U' R'",
  "R U R' U' M' U R U' r'",
  "R U2 R' U' R U R' U' R U' R'",
  "R U2 R2 U' R2 U' R2 U2 R",
  "R2 D' R U2 R' D R U2 R",
  "r U R' U' r' F R F'",
  "F' r U R' U' r' F R",
  "R U2 R' U' R U' R'",
  "R U R' U R U2 R'",
  "R U2 R2 F R F' U2 R' F R F'",
  "r U r' U2 r U2 R' U2 R U' r'",
  "r' R2 U R' U r U2 r' U M'",
  "M U' r U2 r' U' R U' R' M'",
  "F R' F' R2 r' U R U' R' U' M'",
  "r U R' U R U2 r2 U' R U' R' U2 r",
  "r' R U R U R' U' M' R' F R F'",
  "r U R' U' M2 U R U' R' U' M'",
  "R U R' U' R' F R2 U R' U' F'",
  "R U R' U R' F R F' R U2 R'",
  "R U2 R2 F R F' R U2 R'",
  "F R' F' R U R U' R'",
  "F U R U' R' U R U' R' F'",
  "R U R' U R U' B U' B' R'",
  "R' F R U R U' R2 F' R2 U' R' U R U R'",
  "r' U' r U' R' U R U' R' U R r' U r",
  "F U R U' R2 F' R U R U' R'",
  "R' F R U R' F' R F U' F'",
  "l' U' l L' U' L U l' U l",
  "r U r' R U R' U' r U' r'",
  "R' U' F U R U' R' F' R",
  "L U F' U' L' U L F L'",
  "F' U' L' U L F",
  "F U R U' R' F'",
  "R' U' R' F R F' R' F R F' U R",
  "F R U R' U' R U R' U' F'",
  "r U' r2 U r2 U r2 U' r",
  "r' U r2 U' r2 U' r2 U r'",
  "l' U2 L U L' U' L U L' U l",
  "r U2 R' U' R U R' U' R U' r'",
  "r U R' U R U2 r'",
  "l' U' L U' L' U2 l",
  "r U R' U R' F R F' R U2 r'",
  "M' R' U' R U' R' U2 R U' R r'",
  "l' U2 L U L' U l",
  "r U2 R' U' R U' r'",
  "R U R' U' R' F R F'",
  "F R U R' U' F'",
  "L' U' L U' L' U L U L F' L' F",
  "R U R' U R U' R' U' R' F R F'",
];
